# Step 1: Use the official Python 3.8.6 slim image
FROM python:3.8.6-slim

# Step 2: Set the working directory in the container
WORKDIR /app

# Step 3: Install required system dependencies including git, nano, FFmpeg, and PostgreSQL client
RUN apt-get update && \
    apt-get install -y git nano libpq-dev gcc ffmpeg libavutil-dev

# Step 4: Copy the requirements.txt and install the Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Step 5: Copy your application code into the container
COPY . .

# Step 6: Change the working directory to `src/voip` before running the app
WORKDIR /app

# Step 7: Expose the port (if your app uses a specific port)
# EXPOSE 5001

# Step 8: Set the default command to run the app
# CMD ["python", "vad-test.py"]
CMD ["python", "test.py"]