services:
  fastapi-main-global:
    container_name: fastapi-main-global
    hostname: fastapi-main-global
    build:
      context: .
      dockerfile: Dockerfile.mainbackend # Ensure this Dockerfile is correctly placed in the context
    # depends_on:
    #   - postgres
    restart: unless-stopped
    volumes:
      - ./:/app/.
    networks:
      wiselan89: 
        ipv4_address: 192.168.89.109

  audiosocket-101-global:
    container_name: audiosocket-101-global
    hostname: audiosocket-101-global
    # runtime: nvidia
    build: .
    image: audio-socket-base-image-global
    networks:
      wiselan89:
        ipv4_address: 192.168.89.101
    # environment:
    #   - TZ=Asia/Kathmandu
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    volumes:
      - ./:/app/.
    privileged: true

  audiosocket-102-global:
    container_name: audiosocket-102-global
    hostname: audiosocket-102-global
    # runtime: nvidia
    image: audio-socket-base-image-global
    networks:
      wiselan89:
        ipv4_address: 192.168.89.102
    # environment:
    #   - TZ=Asia/Kathmandu
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    volumes:
      - ./:/app/.
    privileged: true
    depends_on:
      - audiosocket-101-global

  audiosocket-103-global:
    container_name: audiosocket-103-global
    hostname: audiosocket-103-global
    # runtime: nvidia
    image: audio-socket-base-image-global
    networks:
      wiselan89:
        ipv4_address: 192.168.89.103
    # environment:
    #   - TZ=Asia/Kathmandu
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    volumes:
      - ./:/app/.
    privileged: true
    depends_on:
      - audiosocket-101-global

  audiosocket-104-global:
    container_name: audiosocket-104-global
    hostname: audiosocket-104-global
    # runtime: nvidia
    image: audio-socket-base-image-global
    networks:
      wiselan89:
        ipv4_address: 192.168.89.104
    # environment:
    #   - TZ=Asia/Kathmandu
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    volumes:
      - ./:/app/.
    privileged: true
    depends_on:
      - audiosocket-101-global

  audiosocket-105-global:
    container_name: audiosocket-105-global
    hostname: audiosocket-105-global
    # runtime: nvidia
    image: audio-socket-base-image-global
    networks:
      wiselan89:
        ipv4_address: 192.168.89.105
    # environment:
    #   - TZ=Asia/Kathmandu
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    volumes:
      - ./:/app/.
    privileged: true
    depends_on:
      - audiosocket-101-global
  
  audiosocket-ne-106-global:
    container_name: audiosocket-ne-106-global
    hostname: audiosocket-ne-106-global
    # runtime: nvidia
    image: audio-socket-base-image-global
    # environment:
    #   - TZ=Asia/Kathmandu
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: "python caller_ne.py" 
    networks:
      wiselan89:
        ipv4_address: 192.168.89.106
    restart: unless-stopped
    volumes:
      - ./:/app/.
    privileged: true
    depends_on:
      - audiosocket-101-global

networks:
  wiselan89:
    external: true

# volumes:
#   postgres-data: